# Generated by Django 3.1.4 on 2020-12-20 14:13

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leaders1',
            fields=[
                ('leadid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, verbose_name='Номер руководителя')),
                ('leadfio', models.CharField(max_length=50, verbose_name='ФИО Руководителя')),
            ],
            options={
                'verbose_name': 'Руководитель проекта',
                'verbose_name_plural': 'Руководители проектов',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('prid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Номер проекта')),
                ('prname', models.CharField(max_length=50, verbose_name='Название дипломного проекта')),
            ],
            options={
                'verbose_name': 'Дипломный проект',
                'verbose_name_plural': 'Дипломные проекты',
            },
        ),
        migrations.CreateModel(
            name='pulpit',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Номер')),
                ('name', models.CharField(max_length=50, verbose_name='Название кафедры')),
                ('phone', models.CharField(max_length=13, verbose_name='Телефон')),
                ('fio', models.CharField(max_length=50, verbose_name='Глава кафедры')),
            ],
            options={
                'verbose_name': 'Кафедра',
                'verbose_name_plural': 'Кафедры',
            },
        ),
        migrations.CreateModel(
            name='Pulpit1',
            fields=[
                ('pulid', models.CharField(default=uuid.uuid4, max_length=50, primary_key=True, serialize=False, verbose_name='Номер кафедры')),
                ('pulname', models.CharField(max_length=50, verbose_name='Название каф.')),
                ('pulphone', models.CharField(max_length=13, verbose_name='Телефон кафедры')),
                ('pulfio', models.CharField(max_length=50, verbose_name='Глава')),
            ],
            options={
                'verbose_name': 'Кафедра предмета',
                'verbose_name_plural': 'Кафедры предметов',
            },
        ),
        migrations.CreateModel(
            name='Reviewers',
            fields=[
                ('revid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Номер')),
                ('revfio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('pulpit_pulname', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pulpit1', verbose_name='Название каф.')),
            ],
            options={
                'verbose_name': 'Рецензент',
                'verbose_name_plural': 'Рецензенты',
            },
        ),
        migrations.CreateModel(
            name='Student',
            fields=[
                ('stid', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Номер')),
                ('stfio', models.CharField(max_length=50, verbose_name='ФИО Студентов')),
                ('group', models.CharField(max_length=10, verbose_name='Группа')),
                ('appraisal', models.CharField(max_length=2, verbose_name='Оценка')),
                ('date', models.CharField(max_length=20, verbose_name='Срок сдачи')),
                ('leaders_fio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.leaders1', verbose_name='Руководитель')),
                ('project_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.project', verbose_name='Дипломный проект')),
                ('reviewers_fio', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.reviewers', verbose_name='Рецензент')),
            ],
            options={
                'verbose_name': 'Студент',
                'verbose_name_plural': 'Студенты',
            },
        ),
        migrations.AddField(
            model_name='leaders1',
            name='pulpit1_pulname',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pulpit1', verbose_name='Название каф.'),
        ),
        migrations.CreateModel(
            name='leaders',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, primary_key=True, serialize=False, verbose_name='Номер')),
                ('fio', models.CharField(max_length=50, verbose_name='ФИО')),
                ('pulpit_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='main.pulpit', verbose_name='Название кафедры')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководители',
            },
        ),
    ]
